<a href="https://colab.research.google.com/github/TuscanoFranzIvan/58013-Linear-Algebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

A = np.array([1, 2, 0])
B = np.array([3, 1, -2])
C = np.array([0, 0, 1])

result1 = A + B + C
print(result1)

result2 = np.add(A, np.add(B, C))
print(result2)

result3 = np.sum(B)
print(result3)

result4 = A - B
print(result4)

result5 = A * B
print(result5)

result6 = np.divide(A, B)
print(result6)


result7 = A / B
print(result7)

C = np.array([3.9, 1.8, 7.7])
D = np.array([1, 1, 1])

result8 = C // D
print(result8)

result9 = np.array(A / B, dtype=int)
print(result9)

[ 4  3 -1]
[ 4  3 -1]
2
[-2  1  2]
[3 2 0]
[ 0.33333333  2.         -0.        ]
[ 0.33333333  2.         -0.        ]
[3. 1. 7.]
[0 2 0]
