<a href="https://colab.research.google.com/github/TuscanoFranzIvan/58013-Linear-Algebra/blob/main/Special_Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Question 1. (20 points) Create a Multiplication Table/Chart of 10 (10x10) using numpy/ python program.

In [23]:
import numpy as np

start = 1
end = 10

numbers = np.arange(start, end + 1)
table = np.zeros((end, end), dtype=int)

for i in range(end):

  table[i, :] = numbers * (i + 1)


for i in range(end):

  for j in range(end):

    print(f"{table[i, j]:2d}", end="\t")

  print()

 1	 2	 3	 4	 5	 6	 7	 8	 9	10	
 2	 4	 6	 8	10	12	14	16	18	20	
 3	 6	 9	12	15	18	21	24	27	30	
 4	 8	12	16	20	24	28	32	36	40	
 5	10	15	20	25	30	35	40	45	50	
 6	12	18	24	30	36	42	48	54	60	
 7	14	21	28	35	42	49	56	63	70	
 8	16	24	32	40	48	56	64	72	80	
 9	18	27	36	45	54	63	72	81	90	
10	20	30	40	50	60	70	80	90	100	


Question 2. (10 points) In relation to Question 1, show a solution that triples all the values of each element

In [24]:
import numpy as np

start = 1
end = 10

numbers = np.arange(start, end + 1)

table = numbers[:, np.newaxis] * np.arange(1, end + 1)
table = table * 3

for row in table:
    for value in row:
        print(f"{value:2d}", end="\t")
    print()

 3	 6	 9	12	15	18	21	24	27	30	
 6	12	18	24	30	36	42	48	54	60	
 9	18	27	36	45	54	63	72	81	90	
12	24	36	48	60	72	84	96	108	120	
15	30	45	60	75	90	105	120	135	150	
18	36	54	72	90	108	126	144	162	180	
21	42	63	84	105	126	147	168	189	210	
24	48	72	96	120	144	168	192	216	240	
27	54	81	108	135	162	189	216	243	270	
30	60	90	120	150	180	210	240	270	300	


Question 3. (10 points) Create a square matrix that has a diagonal of 5's.



In [25]:
import numpy as np

matrix_size = 4
matrix = np.eye(matrix_size) * 5

print(matrix)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


Question 4. (30 points) Create a matrix whose elements are:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [26]:
import numpy as np

matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Question 5. (30 points) Create a result array by subtracting the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

In [27]:
import numpy as np

array1 = np.array([[5, 6, 9], [21, 18, 27]])
array2 = np.array([[15, 33, 24], [4, 7, 1]])

result_array = array1 + array2
result_array_squared = np.square(result_array)

print(result_array_squared)

[[ 400 1521 1089]
 [ 625  625  784]]
