<a href="https://colab.research.google.com/github/TuscanoFranzIvan/58013-Linear-Algebra/blob/main/Vector%2C_Spaces%2C_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vecotr B is', B)

Vector A is [4 3]
Vecotr B is [ 2 -5]


Shape of the Matrix

In [28]:
import numpy as np

### Checking shapes
### Shapes tells us how many rows and columns are there
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
#ball = np.shape([[ball1],[ball2]])
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball+balls
print(z)

[1 2 3]
[ 0  1 -1]
(3, 3)


Addition

In [39]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
R = np.add(A,B)
print(R)

[ 6 -2]


In [43]:
#Subtraction

R = np.subtract(A,B)
print(R)
R = np.subtract(B,A)
print(R)

[2 8]
[-2 -8]


In [46]:
#Multiplication

R = np.multiply(A,B)
print(R)

#Scalar Product
S = np.array([2])
V = S*A
print(V)

[  8 -15]
[8 6]


In [57]:
#Dot Product
A = np.array([4,3])
B = np.array([[2],[-5]])

X = A*B

print(X)


[[  8   6]
 [-20 -15]]


In [73]:
#Property of Matrix
#Identity Matrix
c = np.eye(3,3)
print(c)
d = np.eye(4,4)
print(d)
e = np.eye(5,5)
print(e)

#Zero Matrix
f = np.zeros([5])
print(f)

#Full Matrix
g = np.full((3,3),7)
print(g)

#Transpose Matrix
f  = np.transpose(X)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0. 0. 0. 0. 0.]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
